### ISSUE TITLE
Error in license

### ISSUE THREAD

**Issue by soupdiver** [ryanuber/columnize#11]
I'm working on a project which has a dependency (Consul) which depends on this repository 😬 
There is a license check going on and that fails for your repository.

You provided the MIT license but you miss one line
[See](https://en.wikipedia.org/wiki/MIT_License)

The license must include that line
`Copyright (c) <year> <copyright holders>`

**Comment by ryanuber** [comment]
Thanks @soupdiver! Updated in master 💃

**Comment by soupdiver** [comment]
👏
